// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SampledStreamServer.Database;

#nullable disable

namespace SampledStreamServer.Migrations
{
    [DbContext(typeof(SampledStreamDbContext))]
    [Migration("20221030025731_InitialCreation")]
    partial class InitialCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("SampledStreamServer.Database.Hashtag", b =>
                {
                    b.Property<int>("HashtagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("HashtagId");

                    b.ToTable("Hashtags");
                });

            modelBuilder.Entity("SampledStreamServer.Database.HashtagOccurrence", b =>
                {
                    b.Property<int>("HashtagOccurrenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HashtagId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimeOfOccurrence")
                        .HasColumnType("TEXT");

                    b.HasKey("HashtagOccurrenceId");

                    b.HasIndex("HashtagId");

                    b.ToTable("HashtagOccurrence");
                });

            modelBuilder.Entity("SampledStreamServer.Database.SummaryData", b =>
                {
                    b.Property<int>("SummaryDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("TotalTweets")
                        .HasColumnType("INTEGER");

                    b.HasKey("SummaryDataId");

                    b.ToTable("SummaryDatas");
                });

            modelBuilder.Entity("SampledStreamServer.Database.HashtagOccurrence", b =>
                {
                    b.HasOne("SampledStreamServer.Database.Hashtag", "Hashtag")
                        .WithMany("ObservedTimes")
                        .HasForeignKey("HashtagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hashtag");
                });

            modelBuilder.Entity("SampledStreamServer.Database.Hashtag", b =>
                {
                    b.Navigation("ObservedTimes");
                });
#pragma warning restore 612, 618
        }
    }
}
